---
- name: 'Instala pacotes para o serviço'
  apt:
    name: ['mysql-server-5.6', 'python-mysqldb']
    state: latest
  become: yes
      
- name: 'Criar o banco MySQL'
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present

- name: 'Criar usuario de acesso ao banco'
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ wp_host_ip }}"

- name: 'Configura o mysql para aceitar conexao remota'
  copy:
    src: 'files/my.cnf'
    dest: '/etc/mysql/my.cnf'
  become: yes
  notify:
    - restart mysql