apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx-color-blue
spec:
  selector:
    matchLabels:
      app: deploy-color-blue
  template:
    metadata:
      labels:
        app: deploy-color-blue
    spec:
      containers:
      - name: deploy-color-blue
        image: teclinux/site-color:blue