apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-teclinux-tk-cert
spec:
  secretName: teclinux-tk-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-producao
  dnsNames:
    - "teclinux.tk"    