---
- name: "Download do pacote Wordpress"
  get_url:
    url: "https://wordpress.org/latest.tar.gz"
    dest: "/tmp/wordpress.tar.gz"

- name: "Descompacta o instalador"
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www
    remote_src: yes
  become: yes

- name: "Copiando arquivo de configuração"
  copy:
    src: "{{ wp_instalation_dir }}/wp-config-sample.php"
    dest: "{{ wp_instalation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: "Alterando variaveis de ambiente"
  replace:
    path: "{{ wp_instalation_dir }}/wp-config.php"
    regexp: "database_name_here"
    replace: "{{ wp_db_name }}"
    # regexp: "{{ item.regex }}"
    # replace: "{{ item.value }}"
    # with_items:
    #   - { regex: "database_name_here", value: "{{ wp_db_name }}" }
    #   - { regex: "username_here", value: "{{ wp_username }}" }
    #   - { regex: "password_here", value: "{{ wp_user_password }}" }
    #   - { regex: "localhost", value: "{{ wp_db_ip }}" }
  become: yes

- name: "Copiando arquivo do apache2"
  template:
    src: "templates/000-default.conf.j2"
    dest: "/etc/apache2/sites-available/000-default.conf"
  become: yes
  notify:
    - restart apache
